import type { Component } from "vue";
import {
  Activity,
  Blocks,
  Box,
  Bone,
  BookOpen,
  BrickWall,
  Candy,
  CircleDashed,
  Droplet,
  Droplets,
  Dumbbell,
  Filter,
  Footprints,
  Gem,
  GitBranch,
  Heart,
  HeartPulse,
  Landmark,
  Layers,
  Leaf,
  LeafyGreen,
  ListChecks,
  Microscope,
  Network,
  PawPrint,
  PersonStanding,
  Puzzle,
  Repeat,
  Ruler,
  Shield,
  Spline,
  Sprout,
  SquareStack,
  Star,
  Target,
  TreeDeciduous,
  Trophy,
  Waves,
  Wheat,
  Wind,
  Zap,
} from "lucide-vue-next";

export const LUCIDE = {
  microscope: Microscope,
  leaf: Leaf,
  sprout: Sprout,
  ruler: Ruler,
  repeat: Repeat,
  layers: Layers,
  "git-branch": GitBranch,
  box: Box,
  wheat: Wheat,
  "tree-deciduous": TreeDeciduous,
  blocks: Blocks,
  "brick-wall": BrickWall,
  "leafy-green": LeafyGreen,
  shield: Shield,
  puzzle: Puzzle,
  spline: Spline,
  gem: Gem,
  droplets: Droplets,
  filter: Filter,
  "paw-print": PawPrint,
  "square-stack": SquareStack,
  dumbbell: Dumbbell,
  "person-standing": PersonStanding,
  waves: Waves,
  heart: Heart,
  "heart-pulse": HeartPulse,
  network: Network,
  droplet: Droplet,
  donut: Candy,
  bone: Bone,
  "circle-dashed": CircleDashed,
  target: Target,
  zap: Zap,
  candy: Candy,
  landmark: Landmark,
  footprints: Footprints,
  wind: Wind,
  activity: Activity,
  "book-open": BookOpen,
  "list-checks": ListChecks,
  trophy: Trophy,
  star: Star,
} satisfies Record<string, Component>;

export type IconName = keyof typeof LUCIDE;

export function iconFor(name: string): Component {
  return LUCIDE[name as IconName] ?? Microscope;
}
